apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeprogress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeprogress
  template:
    metadata:
      labels:
        app: codeprogress
    spec:
      containers:
        - name: codeprogress
          image: wesleywillians/codeprogress
          ports:
            - containerPort: 8000
---
    
apiVersion: v1
kind: Service
metadata:
  name: codeprogress-service
  labels:
    app: codeprogress
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-svc
      port: 8000
  selector:
    app: codeprogress
